### ISSUE TITLE
Metadata problem when initializing API

### ISSUE THREAD

**Issue by krzysztof-jelski** [SimplyVC/polkadot_api_server#14]
Hi, I had a working setup of API Server connected to a Kusama validator. Now it stopped working, with the following found in API Server logs.

I believe Kusama received a runtime upgrade 2024 -> 2025, which brings V12 version of Metadata, so probably there's some update needed to support it.

```2020-10-09 12:55:10        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
/opt/polkadot_api_server/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
    at createTypeUnsafe (/opt/polkadot_api_server/node_modules/@polkadot/types/create/createType.js:69:11)
    at Rpc._formatOutput (/opt/polkadot_api_server/node_modules/@polkadot/rpc-core/index.js:327:40)
    at MapSubscriber.project (/opt/polkadot_api_server/node_modules/@polkadot/rpc-core/index.js:186:364)
    at MapSubscriber._next (/opt/polkadot_api_server/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/opt/polkadot_api_server/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/opt/polkadot_api_server/node_modules/rxjs/internal/operators/switchMap.js:89:26)
    at InnerSubscriber._next (/opt/polkadot_api_server/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/opt/polkadot_api_server/node_modules/rxjs/internal/Subscriber.js:66:18)
    at CombineLatestSubscriber.notifyNext (/opt/polkadot_api_server/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
    at InnerSubscriber._next (/opt/polkadot_api_server/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
Connecting to ws://10.0.0.1:9944
2020-10-09 12:57:30        API/INIT: RPC methods not decorated: grandpa_subscribeJustifications, grandpa_unsubscribeJustifications
2020-10-09 12:57:30        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
2020-10-09 12:57:30        API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
    at EventEmitter.value (/opt/polkadot_api_server/node_modules/@polkadot/api/base/Init.js:77:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
API running on port 3000
Received request for /api/pingNode?websocket=ws%3A%2F%2F10.0.0.1%3A9944
Received request for /api/getConnectionsList
Received request for /api/rpc/system/chain?websocket=ws%3A%2F%2F10.0.0.1%3A9944
Received request for /api/pingApi
Received request for /api/derive/staking/validators?websocket=ws://10.0.0.1:9944
Connecting to ws://10.0.0.1:9944
2020-10-09 13:19:34        API/INIT: RPC methods not decorated: grandpa_subscribeJustifications, grandpa_unsubscribeJustifications
2020-10-09 13:19:35        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
2020-10-09 13:19:35        API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
    at EventEmitter.value (/opt/polkadot_api_server/node_modules/@polkadot/api/base/Init.js:77:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11
```

Running from docker, image `simplyvc/polkadot_api_server:1.23.1`.

**Comment by dillu24** [comment]
Hi @krzysztof-jelski ,

Thanks for opening up an issue, we will look into this. Most probably this happened because there are new releases of the polkadot-js/api that need to be supported for the API server to work with the latest upgrades in Kusama.

**Comment by dillu24** [comment]
This should be solved now with the latest release.
