### ISSUE TITLE
Failing on latest Kusama runtime

### ISSUE THREAD

**Issue by krzysztof-jelski** [SimplyVC/polkadot_api_server#21]
Hi, the API fails to initialise after latest runtime upgrade on Kusama.

Logs:
```
2021-01-28 09:09:53        API/INIT: RPC methods not decorated: sync_state_genSyncSpec, system_addLogFilter, system_resetLogFilter, system_syncState
Unknown types found, no types for BlockWeights, ConsumedWeight
Unable to resolve type BlockWeights, it will fail on construction
2021-01-28 09:09:54        API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/opt/polkadot_api_server/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/opt/polkadot_api_server/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Runtime upgrade:
https://polkascan.io/kusama/event/5961600-1
https://polkascan.io/kusama/runtime/2027

**Comment by dillu24** [comment]
Hi @krzysztof-jelski . Thanks for your issue, we have been notified about this. We will work on it asap.
