### ISSUE TITLE
{"error":"TypeError: Cannot read property 'api' of undefined"}

### ISSUE THREAD

**Issue by dmpierre** [SimplyVC/polkadot_api_server#23]
Hello :) 

I'm running a kusama validator node using docker:

```
sudo docker run -d parity/polkadot:latest --validator \
--pruning=archive --ws-port=9944 --unsafe-ws-external \
--rpc-cors=all --name 'My node name' --chain kusama \
--telemetry-url 'wss://telemetry-backend.w3f.community/submit 1'
```

I also setup the polkadot API server using the docker image:

```
sudo docker run -p 3000:3000 -v PATH_TO_CONFIG_FOLDER:/opt/polkadot_api_server/config:ro -d simplyvc/polkadot_api_server:1.26.1
```

When setuping the polkadot server I provided different node addresses using either `localhost`, `127.0.0.1` or the machine actual IP. Also, same with curl calls for which I tried different `MACHINE_ADDRESS` and `NODE_IP`:

```
curl -X GET http://MACHINE_ADDRESS:3000/api/pingNode?websocket=ws://NODE_IP:9944
```

Yet, I keep getting this returned:

```
{"error":"TypeError: Cannot read property 'api' of undefined"}
```

Which value should I provide for the addresses? Which part did I do wrong?

Thanks for the insights!

**Comment by dillu24** [comment]
Hi @pierre-ai , thanks for your question. 

Can you show us a snapshot of the logs when the API server starts, and a copy of the `nodes_config`? 

That error essentially means that the node you are connecting to was not set-up in the API server.

**Comment by dillu24** [comment]
Going to close this for now as it was not followed up.

**Comment by stewartventures** [comment]
hi - I am now receiving this same error after no changes. did the recent runtime upgrade affect this? here is the log output:

2021-10-12 18:46:36        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0e010b000c1c7370… on metadata:: decodeU8a: failed at 0xcc1853797374656d… on pallets: Vec<PalletMetadataV14>:: decodeU8a: failed at 0x1853797374656d01… on : {"name":"Text","storage":"Option<PalletStorageMetadataV14>","calls":"Option<PalletCallMetadataV14>","events":"Option<PalletEventMetadataV14>","constants":"Vec<PalletConstantMetadataV14>","errors":"Option<PalletErrorMetadataV14>","index":"u8"}:: decodeU8a: failed at 0x011853797374656d… on storage: Option<PalletStorageMetadataV14>:: decodeU8a: failed at 0x401c4163636f756e… on items: Vec<StorageEntryMetadataV14>:: decodeU8a: failed at 0x04e8205468652066… on : {"name":"Text","modifier":"StorageEntryModifierV14","type":"StorageEntryTypeV14","fallback":"Bytes","docs":"Vec<Text>"}:: decodeU8a: failed at 0x68652066756c6c20… on modifier: {"_enum":{"Optional":0,"Default":1,"Required":2}}:: Unable to create Enum via index 104, in Optional, Default, Required
2021-10-12 18:46:36        API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: decodeU8a: failed at 0x0e010b000c1c7370… on metadata:: decodeU8a: failed at 0xcc1853797374656d… on pallets: Vec<PalletMetadataV14>:: decodeU8a: failed at 0x1853797374656d01… on : {"name":"Text","storage":"Option<PalletStorageMetadataV14>","calls":"Option<PalletCallMetadataV14>","events":"Option<PalletEventMetadataV14>","constants":"Vec<PalletConstantMetadataV14>","errors":"Option<PalletErrorMetadataV14>","index":"u8"}:: decodeU8a: failed at 0x011853797374656d… on storage: Option<PalletStorageMetadataV14>:: decodeU8a: failed at 0x401c4163636f756e… on items: Vec<StorageEntryMetadataV14>:: decodeU8a: failed at 0x04e8205468652066… on : {"name":"Text","modifier":"StorageEntryModifierV14","type":"StorageEntryTypeV14","fallback":"Bytes","docs":"Vec<Text>"}:: decodeU8a: failed at 0x68652066756c6c20… on modifier: {"_enum":{"Optional":0,"Default":1,"Required":2}}:: Unable to create Enum via index 104, in Optional, Default, Required
    at EventEmitter.value (/home/[removed]/polkadot_api_server/node_modules/@polkadot/api/base/Init.cjs:84:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
