### ISSUE TITLE
Latest Kusama updates broke the api server.

### ISSUE THREAD

**Issue by bjweaver** [SimplyVC/polkadot_api_server#28]
I'm seeing the following errors trying to start the API server.

2021-06-08 22:15:30        REGISTRY: Unable to resolve type MessageId, it will fail on construction
2021-06-08 22:15:31        API/INIT: RPC methods not decorated: state_getChildReadProof
2021-06-08 22:15:31        API/INIT: Error: FATAL: Unable to initialize the API: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at EventEmitter.value (/opt/polkadot_api_server/node_modules/@polkadot/api/base/Init.cjs:91:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-08 22:15:31        API/INIT: Error: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)

**Comment by dillu24** [comment]
Hi @bjweaver , this issue should be resolved with the new update.
