### ISSUE TITLE
{"error":"TypeError: Cannot read property 'api' of undefined"}

### ISSUE THREAD

**Issue by stewartventures** [SimplyVC/polkadot_api_server#37]
hi - I am now receiving this same error after no changes and the system was running fine until 12ET today. did the recent runtime upgrade affect this? here is the log output:

2021-10-12 18:46:36        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0e010b000c1c7370… on metadata:: decodeU8a: failed at 0xcc1853797374656d… on pallets: Vec<PalletMetadataV14>:: decodeU8a: failed at 0x1853797374656d01… on : {"name":"Text","storage":"Option<PalletStorageMetadataV14>","calls":"Option<PalletCallMetadataV14>","events":"Option<PalletEventMetadataV14>","constants":"Vec<PalletConstantMetadataV14>","errors":"Option<PalletErrorMetadataV14>","index":"u8"}:: decodeU8a: failed at 0x011853797374656d… on storage: Option<PalletStorageMetadataV14>:: decodeU8a: failed at 0x401c4163636f756e… on items: Vec<StorageEntryMetadataV14>:: decodeU8a: failed at 0x04e8205468652066… on : {"name":"Text","modifier":"StorageEntryModifierV14","type":"StorageEntryTypeV14","fallback":"Bytes","docs":"Vec<Text>"}:: decodeU8a: failed at 0x68652066756c6c20… on modifier: {"_enum":{"Optional":0,"Default":1,"Required":2}}:: Unable to create Enum via index 104, in Optional, Default, Required
2021-10-12 18:46:36        API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: decodeU8a: failed at 0x0e010b000c1c7370… on metadata:: decodeU8a: failed at 0xcc1853797374656d… on pallets: Vec<PalletMetadataV14>:: decodeU8a: failed at 0x1853797374656d01… on : {"name":"Text","storage":"Option<PalletStorageMetadataV14>","calls":"Option<PalletCallMetadataV14>","events":"Option<PalletEventMetadataV14>","constants":"Vec<PalletConstantMetadataV14>","errors":"Option<PalletErrorMetadataV14>","index":"u8"}:: decodeU8a: failed at 0x011853797374656d… on storage: Option<PalletStorageMetadataV14>:: decodeU8a: failed at 0x401c4163636f756e… on items: Vec<StorageEntryMetadataV14>:: decodeU8a: failed at 0x04e8205468652066… on : {"name":"Text","modifier":"StorageEntryModifierV14","type":"StorageEntryTypeV14","fallback":"Bytes","docs":"Vec<Text>"}:: decodeU8a: failed at 0x68652066756c6c20… on modifier: {"_enum":{"Optional":0,"Default":1,"Required":2}}:: Unable to create Enum via index 104, in Optional, Default, Required
    at EventEmitter.value (/home/[removed]/polkadot_api_server/node_modules/@polkadot/api/base/Init.cjs:84:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

_Originally posted by @sekoyalabs in https://github.com/SimplyVC/polkadot_api_server/issues/23#issuecomment-941288329_

**Comment by dillu24** [comment]
Most probably this is due to the latest upgrade on Kusama/Polkadot. Stay tuned for a new release.

**Comment by Ismael034** [comment]
Hi @dillu24 

Any update on this? The API server is currently not working (giving `{"error":"TypeError: Cannot read property 'api' of undefined"}`) , at least with SORA validators. 

From the docker logs I am just getting  `API-WS: disconnected from ws://localhost:9944: 1006:: connection failed` multiple times every minute. Pretty sure the node is configured correctly as I can curl the node directly and get a response.

Dont hesitate to ask if you need any help testing or want logs/config files

Thanks
